### PR TITLE
fix(test) Use custom atoum runner everywhere, so…

### LINKED ISSUE #10: Don't always run atoum help/usage
Don't run the atoum help usage when there is no test to execute

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/46911019-don-t-always-run-atoum-help-usage?utm_campaign=plugin&utm_content=tracker%2F57171363&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57171363&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Hywan**
… so that we can remove the atoum's help/usage when there is no test to
run.

Fix #10.

### CODE REVIEW

**Comment by Hywan** [comment]
Not ready to merge.

File: src/Bin/Atoum.php [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+ * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+ * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+ * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+ * POSSIBILITY OF SUCH DAMAGE.
+ */
+
+namespace Kitab\Bin;
+
+use Hoa\Console;
+use Hoa\File\Temporary\Temporary;
```
Comment (Hywan) [inline src/Bin/Atoum.php]: Can be removed.

File: src/DocTest/Runner.php [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+ * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+ * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+ * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+ * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+ * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+ * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+ * POSSIBILITY OF SUCH DAMAGE.
+ */
+
+require_once
```
Comment (Hywan) [inline src/DocTest/Runner.php]: Could fail if Kitab is a dependency.
